<Project Sdk="Microsoft.NET.Sdk">  

 <PropertyGroup>  
   <TargetFramework>net6.0</TargetFramework>  
   <ImplicitUsings>enable</ImplicitUsings>  
   <Nullable>enable</Nullable>  
   <LangVersion>preview</LangVersion>
   <AllowUnsafeBlocks>True</AllowUnsafeBlocks>  
   <RuntimeIdentifier>win-x64</RuntimeIdentifier>  
   <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
   <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnablePackageValidation>true</EnablePackageValidation>
   <LEMelonLoaderPath>$(LE_ML)</LEMelonLoaderPath>
 </PropertyGroup>  

 <ItemGroup>  
   <Reference Include="0Harmony, Version=2.10.2.0, Culture=neutral, processorArchitecture=MSIL">  
     <SpecificVersion>False</SpecificVersion>  
    <HintPath>$(LEMelonLoaderPath)\net6\0Harmony.dll</HintPath>  
   </Reference>
   <!-- <Reference Include="Il2CppDMM">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppDMM.dll</HintPath>  
   </Reference> -->
   <Reference Include="Il2CppInterop.Common">  
    <HintPath>$(LEMelonLoaderPath)\net6\Il2CppInterop.Common.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppInterop.Generator">  
    <HintPath>$(LEMelonLoaderPath)\net6\Il2CppInterop.Generator.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppInterop.Runtime">  
    <HintPath>$(LEMelonLoaderPath)\net6\Il2CppInterop.Runtime.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppLE">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppLE.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppLE.Telemetry.Client">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppLE.Telemetry.Client.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppLE.Telemetry">
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppLE.Telemetry.dll</HintPath>
   </Reference>
   <Reference Include="Il2CppLidgren.Network">
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppLidgren.Network.dll</HintPath>
   </Reference>
   <Reference Include="Il2CppFacepunch.Steamworks.Win64">
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppFacepunch.Steamworks.Win64.dll</HintPath>
   </Reference>
   <Reference Include="Il2Cppmscorlib">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppSystem">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppSystem.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppSystem.Core">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>  
   </Reference>
   <Reference Include="Il2CppSirenix.Serialization">
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\Il2CppSirenix.Serialization.dll</HintPath>
   </Reference>
   <Reference Include="MelonLoader">  
    <HintPath>$(LEMelonLoaderPath)\net6\MelonLoader.dll</HintPath>  
   </Reference>
   <Reference Include="UnityEngine.CoreModule">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>  
   </Reference>
   <Reference Include="UnityEngine.ImageConversionModule">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>  
   </Reference>
   <Reference Include="UnityEngine.IMGUIModule">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>  
   </Reference>  
   <Reference Include="UnityEngine.InputLegacyModule">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>  
   </Reference>
   <Reference Include="UnityEngine.TextRenderingModule">
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
   </Reference>
   <Reference Include="UnityEngine.Physics">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>  
   </Reference>
   <Reference Include="UnityEngine.UI">  
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>  
   </Reference>
   <Reference Include="UnityEngine.UIModule">
    <HintPath>$(LEMelonLoaderPath)\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
   </Reference>
 </ItemGroup>  

 <ItemGroup>  
   <Folder Include="Models\" />  
 </ItemGroup>  

</Project>
